package:
    name: cdat-changelogger
    version: 0.10

source:
    git_rev: cleanup
    git_url: git://github.com/UV-CDAT/changelogger.git

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
   - python
   - cffi
   - cryptography
   - enum34
   - gnureadline
   - ipython
   - ndg-httpsclient
   - pyopenssl
   - pyasn1
   - pycparser
   - requests
   - six
   - urllib3
   - wsgiref

about:
    home:  http://gitub.com/UV-CDAT/cdms


