package:
    name: cdat-changelogger
    version: 0.10

source:
    git_rev: cleanup
    git_url: git://github.com/CDAT/changelogger.git

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
   - python
   - requests

about:
    home:  http://gitub.com/CDAT/cdms


